XiopiaWorkTimeTracker/XiopiaWorkTimeTracker/Models/ViewModels/ReportingViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using XiopiaWorkTimeTracker.Models.Database;

namespace XiopiaWorkTimeTracker.Models.ViewModels
{
    public class ReportingViewModel
    {
        public ReportingViewModel()
        {
            this.UserList = new List<SelectListItem>();
            this.AllProjects = new List<SelectListItem>();
        }

        public List<SelectListItem> UserList { get; set; }
        public List<SelectListItem> AllProjects { get; set; }
        public int SelectedUser { get; set; }
        public int SelectedProject { get; set; }

        [Required]
        public DateTime From { get; set; }
        public DateTime Until { get; set; }
    }
}

XiopiaWorkTimeTracker/XiopiaWorkTimeTracker/Controllers/ReportingController.cs
using System.Web.Mvc;
using XiopiaWorkTimeTracker.Models.Repositories;
using XiopiaWorkTimeTracker.Models.ViewModels;
using Ressources;
using System;

namespace XiopiaWorkTimeTracker.Controllers
{
    public class ReportingController : Controller
    {

        private UserRepository _usersRepository = null;
        private ProjectsRepository _projectsRepo = null;

        public ReportingController()
        {
            _usersRepository = new UserRepository();
            _projectsRepo = new ProjectsRepository();
        }
        
        // GET: Reporting
        public ActionResult Index()
        {
            ReportingViewModel viewModel = new ReportingViewModel();
            viewModel.From = DateTime.Now;
            viewModel.Until = DateTime.Now;
            return View(FillLists(viewModel));
        }

        [HttpPost]
        public ActionResult Search(ReportingViewModel model)
        {
            if(model.From > model.Until)
            {
                ModelState.AddModelError("Until", Language.ErrorUntilBeforeFrom);
            }
            if(ModelState.IsValid)
            {

            }
            return View("Index", FillLists(model));
        }

        private ReportingViewModel FillLists(ReportingViewModel model)
        {
            var users = this._usersRepository.GetAll();
            if (users != null)
            {
                model.UserList.Add(new SelectListItem() { Value = "0", Text = Language.AllUsers, Selected = true });
                foreach (var user in users)
                {
                    model.UserList.Add(new SelectListItem() { Value = user.Id.ToString(), Text = user.FirstName + " " + user.LastName });
                }
            }
            var projects = this._projectsRepo.GetAll();
            model.AllProjects.Add(new SelectListItem() { Value = "0", Text = Language.AllProjects, Selected = true });
            foreach (var project in projects)
            {
                model.AllProjects.Add(new SelectListItem() { Value = project.Id.ToString(), Text = project.Name });
            }
            return model;
        }
    }
}

XiopiaWorkTimeTracker/XiopiaWorkTimeTracker/Views/Reporting/Index.cshtml
@using Ressources
@using XiopiaWorkTimeTracker.Models.ViewModels
@model ReportingViewModel

<script type="text/javascript" src="~/Scripts/jquery-1.10.2.min.js"></script>

<header>
    <h1>@Language.BackofficeReporting</h1>
</header>

@using (Html.BeginForm("Search", "Reporting", FormMethod.Post))
{
    <div class="container">
        <div class="row">
            <h3>@Language.SearchFor</h3>
        </div>
        <div class="row">
            <div class="col-lg-2">
                <h3>@Language.Employee</h3>
                @Html.DropDownListFor(u => u.SelectedUser, Model.UserList)
            </div>
            <div class="col-lg-2">
                <h3>@Language.Project</h3>
                @Html.DropDownListFor(p => p.SelectedProject, Model.AllProjects)
            </div>
            <div class="col-lg-2">
                <h3>@Language.from</h3>
                @*@Html.TextBoxFor(f => f.From, ViewData.TemplateInfo.FormattedModelValue.ToString(), new { type = "date", @class = "form-control" })*@
                <input type="date" name="From" value="@Model.From"/>
                @Html.ValidationMessageFor(f => f.From)
            </div>
            <div class="col-lg-2">
                <h3>@Language.until</h3>
                <input type="date" name="Until" value=@Model.Until.ToString()/>
                @Html.ValidationMessageFor(u => u.Until)
            </div>
            <div class="col-lg-2">&nbsp;</div>
            <div class="col-lg-2">&nbsp;</div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <input type="submit" value=@Language.Search style="margin:15px" />
            </div>
        </div>
    </div>
}

<div class="container">
    @*<div class="row">
            <div class='col-sm-6'>
                <div class="form-group">
                    <div class='input-group date' id='datetimepicker3'>
                        <input type='text' class="form-control" />
                        <span class="input-group-addon">
                            <span class="glyphicon glyphicon-time"></span>
                        </span>
                    </div>
                </div>
            </div>
            <script type="text/javascript">
                $(document).ready(function () {
                    $('#datetimepicker3').datetimepicker({
                        format: 'LT'
                    });
                });
            </script>
        </div>*@
</div>